### ISSUE TITLE
Pod Creation for having Cluster autoscaling tested at scale

### ISSUE THREAD

**Issue by saiyam1814** [litmuschaos/litmus#1171]
In order to test the Cluster Autoscaler capabilities, there should be an experiment that should spawn some pods to verify is autoscaling is working fine. This test can run in a timely manner and keeps on creating pod creating chaos.

**Comment by rahulchheda** [comment]
Every Chaos Experiment, works in like a Hypothesis. Where you describe a scenario or a case, with a set of parameters, which help you validate if your application is reselient to that Chaos Experiment. So, in order to validate that, a desired behavior has to be determined, and then your application is compared to that behavior/ set of parameters to judge if your application is reselient to that Chaos.
So, in order to make this a Chaos Experiment, some sort of Exit Criteria has to defined.
For that, we need some post checks (after chaos) to validate the resiliency of your application. 
What can be the post-checks or Exit Criteria of this type of Experiment? 
cc: @ksatchit

**Comment by saiyam1814** [comment]
in order to test a specific autoscaling scenario, whenever a pod goes in Pending Autoscaler will kick in and the pod describe would show triggeredscaleup or didn't triggered scaleup and will remain in pending unless a new node joins the cluster. The easiest way would be to create Pending pods have a grace period or timeout for say 15 minutes and then again check the status of the pods that were spawned by the experiment. If all are running means autoscaling worked fine

**Comment by uditgaurav** [comment]
Hey @saiyam1814 Thanks for raising the feature request. We are tracking this issue for 1.7.0. Here is the pull request for the autoscaling test (https://github.com/litmuschaos/litmus-go/pull/65)  feel free to give your thought on this.

**Comment by saiyam1814** [comment]
Wow this is nice to hear, I will check this out 👍

**Comment by saiyam1814** [comment]
Here is the blog featuring the pod-autoscaler experiment - https://www.civo.com/learn/chaos-engineering-kubernetes-litmus

**Comment by ksatchit** [comment]
Awesome - thanks for the cool blog @saiyam1814 !!
