### ISSUE TITLE
(feat): Add support for DeploymentConfig object

### ISSUE THREAD

**Issue by andreas131989** [litmuschaos/litmus#1406]
Currently the supported objects in `.spec.appinfo.appkind` are `deployment|statefulset|daemonset`.

For Openshift users, there is an additional workload object, DeploymentConfig which is specified in the Openshift API (https://docs.openshift.com/container-platform/3.11/rest_api/oapi/v1.DeploymentConfig.html#object-schema) which is similar to Deployments with minor changes. 
(A comparison is here https://docs.openshift.com/container-platform/4.1/applications/deployments/what-deployments-are.html) 

This feature is to add support for DeploymentConfigs as well to perform experiments.

**Comment by ksatchit** [comment]
Hey @andreas131989 could you share which experiments are mainly looking at running at this point?

**Comment by ksatchit** [comment]
@andreas131989 , at the outset, as you may have noticed, the error you see arises from the OpenAPI validation of the engine custom resource not allowing deploymentConfigs. Which in turn is set up that way because the controller doesn't support it (or other OpenShift resources yet. Most of the usecases where litmus is used on OpenShift is w/ standard K8s resources).

However, have been thinking about this. Here is one of the ways you could use to get experiments running on deploymentConfigs even before we add native support for OpenShift resources completely. Make the following changes in the ChaosEngine spec. 

- (a) Set value of  `.spec.annotationCheck` to `false`. 

   - Today we use the `appkind` flag to filter resources  by type/kind & check if they are annotated for chaos. The annotation is **one** of the ways to ensure a lower blast radius and isolate chaos to a particular app rather than randomly select multiple apps. The `appkind` is not really used beyond this point. It is the labels that are used to detect "pods" (actual units which are subjected to chaos) of the specified application. The same net-effect can be achieved via **unique** labels used for the selectors in the deploymentConfig template. By unique, we mean labels which are present only on those apps you would like to kill/perform chaos upon. This way, though we don't do annotation checks we are still effectively managing the blast radius. 

- (b) Avoid usage `spec.appinfo.appkind` of flag. 
  - i.e., the `spec.appinfo` will consist only of `appns` & `applabels`. This will prevent the OpenAPI spec from calling out an unsupported resource type. With (a) we are already not using appkind.

**Comment by andreas131989** [comment]
@ksatchit , thanks for the elaborate input! Indeed, this workaround would unblock me for now,  cheers. for that! I would still though like eventually to use the annotation. so I hope the Openshift objects will be supported in the future!

**Comment by ksatchit** [comment]
Sure @andreas131989 ! Have added the next milestone 1.4 as the feature date for this 👍. 
We are looking at better native support for OpenShift (maybe a separate operator image/yaml manifest) considering the use of different api set and security constraints.

**Comment by rajdas98** [comment]
@ksatchit @andreas131989 I would like to contribute in adding the openshift support. Feel free to assign me

**Comment by ksatchit** [comment]
Thanks @rajdas98 . Done!

**Comment by ksatchit** [comment]
Fixed via https://github.com/litmuschaos/chaos-operator/pull/199 in 1.4 release.
