### ISSUE TITLE
Annotation support via Custom resource 

### ISSUE THREAD

**Issue by sumitnagal** [litmuschaos/litmus#1421]
## Is this a BUG REPORT or FEATURE REQUEST?
Feature Request
 
 Choose one: BUG REPORT or FEATURE REQUEST
As we are building admin use case, target namespace might have AWS IAM role access. To get this access from admin use case we need a capability to send the annotation of Target IAM roles via Custom resource, so that when we can runner and engine, they honor the annotation of IAM roles. This is a use case for AWS, but it might application to other use cases too. We should be override the annotation as well as send the annotation. 

**What happened**:
EC2 use case for terminate a pod from different namespace. 

**What you expected to happen**:
There is no way we can pass IAM role information via CR. as well as operator won't pass this to experiment pods.

**How to reproduce it (as minimally and precisely as possible)**:
you can use job and reproduce that, where adiding job for given experiment will work but triggering via chaos litmus operator won't work.  

**Anything else we need to know?**:
We are working on fix, and share the details.

**Comment by ksatchit** [comment]
Based on discussionswith @sumitnagal , the requirement was misunderstood initially. This issue recommends enhancing the operator framework to insert custom annotation into the chaos resources, in other words., _ensure chaos runner, experiment job etc., carry this annotation in their respective pod/job spec._ ..

.. i.e., here the annotations in this context doesn't refer to a filter criteria to derive chaos candidates, instead it is used as an instrumentation into the chaos resources spec to enable/fulfill certain conditions while running on specific platforms/during specific use-cases.

**Comment by ksatchit** [comment]
At first look, this would need following changes: 

- (A) In ChaosExperiment Schema:

  One more entry here after image, say called annotations as an experiment property: 
  https://github.com/litmuschaos/chaos-operator/blob/master/pkg/apis/litmuschaos/v1alpha1/chaosexperiment_types.go#L60

- (B) In ChaosEngine Schema:

  - The corresponding entry here in the `.spec.components.runner.annotations` - as a runner component property: https://github.com/litmuschaos/chaos-operator/blob/master/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go#L124 ---> (better to take as a list to support multiple annotations)

  - The corresponding entry here as `.spec.experiments[index].spec.components.annotations` - https://github.com/litmuschaos/chaos-operator/blob/master/pkg/apis/litmuschaos/v1alpha1/chaosengine_types.go#L156 - as an experiment property (mapped to the chaosexperiment schema in (A))

*Note*: (B) has need for this annotation attribute in 2 distinct places today because we are treating the runner and experiment job as 2 separate entities today with flexibility to control their respective specs..( in future they may be merged into a single entity, but that is a different discussion..)

- (C) The logic in the chaos-operator that constructs the runner spec should build it (i.e., the runner pod spec) with the annotation. This runner builder function should have a WithAnnotation entry here: https://github.com/litmuschaos/chaos-operator/blob/master/pkg/controller/chaosengine/chaosengine_controller.go#L228

- (D) The logic in the chaos-runner that constructs the experiment job should build it (i.e., the experiment job spec) with the annotation. This exp job builder function should have an withAnnotation entry here: https://github.com/litmuschaos/chaos-runner/blob/master/pkg/utils/builders.go#L147 

  (may need to be propagated here too: https://github.com/litmuschaos/chaos-runner/blob/master/pkg/utils/builders.go#L117) (edited)

**Comment by ksatchit** [comment]
*Made some updates/edits to above suggested steps*

**Comment by ksatchit** [comment]
cc: @rahulchheda - could you please add (A) to aid @sumitnagal in going ahead with other subsequent changes. It would be needed regardless of whether the annotation is added into both exp/engine or engine alone.

**Comment by ksatchit** [comment]
This is fixed via 
- https://github.com/litmuschaos/chaos-operator/pull/193, 
- https://github.com/litmuschaos/elves/pull/25,
-  https://github.com/litmuschaos/chaos-runner/pull/62
