### ISSUE TITLE
Apply chaos to an entire namespace

### ISSUE THREAD

**Issue by andreas131989** [litmuschaos/litmus#1523]
It would be a very useful feature if we can specify an entire namespace and apply chaos to all (or a subset/percentage) of the workloads running there. This would allow SRE/Admins people to test a complete environment or functional domain.

Several examples:
- Apply chaos to domainX-prod namespace for 50% of the total workloads
- Apply chaos to PROD namespace for all the deployments with domain=name label
- Apply chaos to PROD namespace for all statefulsets
etc

**Comment by ksatchit** [comment]
That's a cool requirement! Thanks for this issue @andreas131989 !

**Comment by rahulchheda** [comment]
Can I start working on this issue @ksatchit , will create an issue in chaos-operator Repo framing my approach on this.

**Comment by ksatchit** [comment]
This is supported since the 1.8.0 release. If .spec.annotationCheck is set to `false`* & the `.spec.appinfo.applabel` is not specified, the chaos is injected on pods available inside the ns - selection being random and single. by default. However, if we would like more than one pod to be impacted in this scenario - we can use the env PODS_AFFECTED_PERC to specify the blast radius. A value of 100% would target all the pods in the specified ns.
