### ISSUE TITLE
Deleting the litmus operator hangs indefinitely

### ISSUE THREAD

**Issue by cpitstick-argo** [litmuschaos/litmus#1537]
**What happened**:
When trying to upgrade from Litmus 1.3.0 -> 1.4.1, I first ran:

`kubectl delete -f litmus-operator-1.3.0.yaml`

This is to prevent outdated resources from becoming orphaned and cluttering up the cluster. The plan was then to run:

`kubectl apply -f litmus-operator-1.4.0.yaml`

However, the `kubectl delete` command hung indefinitely. I eventually had to use `CTRL+C` to break the command line, leaving me unsure of whether everything was deleted.

**What you expected to happen**:
I expected the resources to be deleted after a reasonable wait period, and then for the application of the latest version to work properly.

Or I expect a procedure that's documented indicating how to uninstall Litmus from a cluster without leaving orphaned resources.

Or I expect a procedure that's documented indicating how to upgrade Litmus, making sure that there are no orphaned resources resulting from an upgrade of one version to the next.

**How to reproduce it (as minimally and precisely as possible)**:
Install Litmus on a cluster, start running an experiment, and while an experiment is running successfully run:

`kubectl delete -f litmus-operator-[version].yaml`

**Anything else we need to know?**:
I discussed this on the Litmus Slack channel with Rahul M Chheda, and he stated this:

"This is caused because of the ChaosEngine finalizer. Make sure that you don't have any stale/ existing ChaosEngines by running `kubectl delete ChaosEngine --all --all-namespaces`"

Even if true, this should be documented as this is important for the upgrade procedure from previous versions. This suggests that with every version release, the Litmus team should post upgrade notes and actually test the upgrade path from the previous version.

**Comment by rahulchheda** [comment]
Just thinking out loud, if we are planning for a stable release of `litmuschaos/admission-controllers`, we can validate/ or catch deletion event of `chaos-operator` via Admission Webhook.
Then we can proceed as follows:
    - Delete the chaosengine manually
    - Don't allow user to delete `chaos-operator`

**Comment by ksatchit** [comment]
This is a good to have, but wouldn't guard us against wholesale operator manifest deletes - the admission controller might be lost by then. IMO this needs a dedicated uninstall job/operator the way many projects are doing currently, including OpenEBS as well as an upgrade job (which is why, I believe, the uninstall was attempted in the first place). 

Until such time, this needs to be documented well enough. There are beginnings of some here, but we need more extensive docs covering that. Putting this out as a 1.5.1 item. 

- https://docs.litmuschaos.io/docs/getstarted/#uninstallation
- https://docs.litmuschaos.io/docs/faq-troubleshooting/#litmus-uninstallation-is-not-successful-and-namespace-is-stuck-in-terminating-state (not very satisfied w/ a medium link from docs, but it is a temp measure)

**Comment by ksatchit** [comment]
There is better elaboration here: https://github.com/litmuschaos/litmus-docs/pull/307

**Comment by ksatchit** [comment]
Closing this issue based on above fix. Upgrade notes will be tracked by a separate issue (https://github.com/litmuschaos/litmus/issues/1335)
