### ISSUE TITLE
bug(hub): Refreshing from any version brings me back to latest version

### ISSUE THREAD

**Issue by uditgaurav** [litmuschaos/litmus#1755]
**COMPONENT NAME**

- Chaos Chart Hub

**SUMMARY**
- After selecting any version from the hub if I do refresh it is taking me back to the latest version. Like if I choose `1.5.0` version and if I do refresh then my version changes to the latest which is 1.6.0. The expectation should be it should be in the same version with a refreshed page?

**LITMUS VERSION**
```
1.6.0
```

**Comment by gdsoumya** [comment]
@uditgaurav we had intentionally did this, because when we were discussing about this it was decided a refresh won't persist the version selection. React doesn't require refreshes during normal flow of actions, it will only refresh if manually done or if we close the tab and visit the website again.
If we want we can persist the version throughout different sessions, but not sure if it is required.

**Comment by uditgaurav** [comment]
Thanks @gdsoumya for looking into it. So you mean if I do some changes and wanted to see if it is getting reflected there or not refresh won't help?

**Comment by uditgaurav** [comment]
This seems to be done intentionally and will enhance in further enhancement. Closing it.
