### ISSUE TITLE
Enhance the chaos-exporter to push metrics to cloudwatch 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/litmus#1890]
- Enable creation of experiment metrics that can be consumed by AWS cloudwatch

**Comment by nrusinko** [comment]
https://github.com/litmuschaos/chaos-exporter/pull/72

Functionality is implemented in a PR above.
In order to store metrics to CloudWatch we use aws-sdk-go lib (github.com/aws/aws-sdk-go/service/cloudwatch)

The following metrics are stored to CloudWatch:
chaosengine_passed_experiments
chaosengine_failed_experiments
chaosengine_experiments_count
chaosengine_waiting_experiments

New environment variables have to added into chaos-exporter.yaml
AWS_CLOUDWATCH_METRIC_NAMESPACE - Namespace in CloudWatch metrics
CLUSTER_NAME - Cluster name where Litmus chaos is configured
APP_NAME - litmus eventrouter app name
AWS_ACCESS_KEY_ID - Access key of AWS account
AWS_SECRET_ACCESS_KEY - Secret key of AWS account
AWS_REGION - CloudWatch region

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/chaos-exporter/pull/72
