### ISSUE TITLE
Need to upgrade docker images to use go1.15

### ISSUE THREAD

**Issue by rajdas66** [litmuschaos/litmus#1959]
Changes:
- Litmus portal components
- Litmus core components

**Comment by DarthBenro008** [comment]
Hey @rajdas98, I think we can upgrade all the `DockerFile` builder stages to go1.16, I would like to work on this, could you assign it to me? 
Additionally, although I do not see any issues that will arise out of the box when upgrading to go1.16, but is there any method or tests that is required to be run to ensure nothing breaks? Or am I good to go by trusting the CI alone?

**Comment by rajdas98** [comment]
Hi @DarthBenro008, Yes, that would be good to upgrade it to the latest version. But we need to check the compatibility with other go pkgs?

**Comment by DarthBenro008** [comment]
@rajdas98 In my opinion that should not be an issue. Because go1.16 just adds more features like introduction of io/fs package and just deprecates ioutil package as mentioned [here](https://golang.org/doc/go1.16). GoLang promises backward compatibility. Hence any package with go1.14 should run smoothly on go1.16, however I'll ensure to check go.mod once.
