### ISSUE TITLE
Merge patching .spec[]Env in chaos experiments overwrites preexisting variables 

### ISSUE THREAD

**Issue by barkardk** [litmuschaos/litmus#1961]
I would like to add the possibility for grafana annotations to be added when ansible in my chaos engines start running, 
Ansible supports enabling annotations to grafana via Environment variables.    
Ideally I would like to be able to merge the environment  variables with my chaosexperiments however, due to the how arrays function in crd my merge patched environment variables overwrite the previous ones that are necessary  for the chaosexperiments.   
To overcome this I have written a pretty hacky script that   
* Dynamically generates the grafana URI needed for the ANSIBLE GRAFANA_URL parameter (this varies between my clusters) 
* Dynamically generates a grafana API key for the ansible GRAFANA_API_KEY parameter 
* Picks up the environment   variables  .spec[].env from the installed experiments and stores them in a temporary array 
* Merges these variables with my ANSIBLE ones 
* Overwrites the .spec[].env variables in the experiments with my new merged array   

Here is the script that I use. It should hopefully clear up what I am trying to achieve
```bash
#!/bin/bash
#######################################################
#
#  kristin.barkardottir
#
######################################################
namespace="${1:-chaos}"
experiment_namespace="${2:-default}"
GRAFANA_ADMIN_PASS=$(kubectl  get secret grafana-admin -n $namespace -o=jsonpath='{.data.GF_SECURITY_ADMIN_PASSWORD}' | base64 -d)
GRAFANA_URL="grafana.${namespace}.svc.cluster.local"
kubectl create serviceaccount nettool
#Use this pod to generate the api key within the cluster
cat << EOF | kubectl apply -f - 
apiVersion: v1
metadata:
  name: nettool
kind: Pod
spec:
   serviceAccount: nettool
   serviceAccountName: nettool
   containers:
    - name: nettool
      image: praqma/network-multitool
EOF
sleep 15
rand="ansible-key-$$"
payload="{\"name\":\"$rand\", \"role\": \"Admin\"}"
GRAFANA_API=$(kubectl exec -it nettool -- curl -X POST -H 'Content-Type: application/json' -d "${payload}"  http://admin:${GRAFANA_ADMIN_PASS}@${GRAFANA_URL}/api/auth/keys)
GRAFANA_API_KEY=$(echo "$GRAFANA_API" | jq '.key' -r)
# These environment variables are used by Ansible to start annotating the experiment runs
joinb='[
 {
   "name":"ANSIBLE_CALLBACK_PLUGINS",
   "value":"callback_grafana_annotations"
 },
 {
   "name":"ANSIBLE_CALLBACK_WHITELIST",
   "value":"timer,grafana_annotations"
 },
 {
   "name":"GRAFANA_VALIDATE_CERT",
   "value":"no"
 },
 {
   "name": "GRAFANA_URL",
   "value": "http://'${GRAFANA_URL}'/api/annotations"
 },
 {
   "name":"GRAFANA_API_KEY",
   "value":"'${GRAFANA_API_KEY}'"
}
]'

for experiment in $(kubectl get chaosexperiment -o jsonpath='{.items[*].metadata.name}' -n $experiment_namespace); do
  joina=$(kubectl get chaosexperiments $experiment -o json -n  $experiment_namespace| jq '.spec[].env')
  joined=$(echo $joina | jq ". + $joinb")
  patch='{"spec":{"definition":{"env":'${joined}'}}}'
	kubectl patch chaosexperiment $experiment --type merge --patch "${patch}" -n $experiment_namespace
done
```

**Comment by ksatchit** [comment]
Thanks @xkbarkar !! Thanks for sharing the workaround. Will get back on this!

**Comment by ksatchit** [comment]
There is a dedicated chaos-exporter that pushes prometheus metrics for the exp-execution (ex: `litmuschaos_awaited_experiment` which indicates the period for which the chaos is active) that can be used for the source for annotations in Grafana. 

Having said that, if there are other attributes derived from the experiment which we need in order to annotate grafana dashboards - they can be accommodated with the exporter itself. This way, they can be leveraged not just in Grafana, but in any other APM that can consume prom metrics. 

Please create a fresh issue with the attributes desired, and we can work on the same. 

Note: The out-of-the-box faults (new name for the erstwhile "experiments") are predominantly re-written in/migrated-to Golang, while the litmus-ansible repo holds references for how to construct an exp in ansible.
