### ISSUE TITLE
User details in My-accounts don't persist

### ISSUE THREAD

**Issue by Saranya-jena** [litmuschaos/litmus#3158]
**What happened**:
The user details - name and email don't persist in their respective text fields.

**What you expected to happen**:
The user details should be displayed in the text fields as default values which can later be edit by the user.

**How to reproduce it (as minimally and precisely as possible)**:
This can be viewed in My-Account tab in Settings section.

**Anything else we need to know?**:
![Screenshot from 2021-08-19 22-52-30](https://user-images.githubusercontent.com/28081206/130114930-90c76701-43a1-4efb-a650-1698830a4931.png)

**Comment by sayantani11** [comment]
Can I work on this?

**Comment by Saranya-jena** [comment]
> Can I work on this?

Sure! Assigning it to you.

**Comment by sayantani11** [comment]
@Saranya-jena Can you tell me how should I start?

**Comment by Saranya-jena** [comment]
Hi @sayantani11 you can start with taking a look at the implementation of `My-Accounts` file:  https://github.com/litmuschaos/litmus/tree/master/litmus-portal/frontend/src/views/Settings/AccountsTab 

You can do the dev setup by referring to this doc : https://github.com/litmuschaos/litmus/wiki/Litmus-Portal-Development-Guide

**Comment by sayantani11** [comment]
Sorry but I don't think I'll be able to continue with the issue. Sorry.
/unassign

**Comment by duttaANI** [comment]
I would like to share my approach for future reference :

I am able to solve this issue partially by editing the following file -

**litmus/litmus-portal/frontend/src/views/Settings/AccountsTab/PersonalDetails/index.tsx**

Partially because the previously set values would be displayed on their respective fields (full name , email ) . However while editing the values , the user will not be able to backspace on the first letter . ( that is if user wants to edit it the following steps are required-

enter a new letter at index 0
Then delete the letter at index 1
 )

**Possible explanation** - empty string or "" is a falsey in typescript . However fullName and email fields as defined in the interface PersonaData are both type string .
Hence while handling changes the handle wont accept a false datatype or empty string  .


some links for reference -

[stack overflow](https://stackoverflow.com/questions/63354408/unable-to-delete-value-character-from-input-reactjs)

(https://github.com/redux-form/redux-form/issues/2537)[https://github.com/redux-form/redux-form/issues/2537]


**Modified code -**

`
import { useMutation, useQuery } from '@apollo/client';
import { Typography } from '@material-ui/core';
import { ButtonFilled, ButtonOutlined, Modal } from 'litmus-ui';
import React, { useState } from 'react';
import { useTranslation } from 'react-i18next';
import Loader from '../../../../components/Loader';
import UserDetails from '../../../../components/UserDetails';
import config from '../../../../config';
import { GET_USER, UPDATE_DETAILS } from '../../../../graphql';
import {
  CurrentUserDedtailsVars,
  CurrentUserDetails,
} from '../../../../models/graphql/user';
import { UpdateUser } from '../../../../models/userData';
import { getToken, getUsername } from '../../../../utils/auth';
import useStyles from './styles';
import { CurrentUserData } from '../../../../models/userData';

interface personaData {
  email: string;
  userName: string;
  fullName: string | "";
}

// Displays the personals details on the "accounts" tab
const PersonalDetails: React.FC = () => {
  const classes = useStyles();
  const { t } = useTranslation();

  const username = getUsername();
  const [loading, setLoading] = React.useState(false);
  // Query to get user details
  const [memberDetails, setMemberDetails] = useState<CurrentUserData>();
  // const { data: dataA } = useQuery<CurrentUserDetails, CurrentUserDedtailsVars>(
  //   GET_USER,
  //   { variables: { username } }
  // );
  const { data: dataA } = useQuery<CurrentUserDetails, CurrentUserDedtailsVars>(GET_USER, {
    variables: { username: username },
    onCompleted: (data) => {
      setMemberDetails({
        name: data.getUser.name,
        uid: data.getUser.id,
        username: data.getUser.username,
        role: data.getUser.role,
        email: data.getUser.email,
      });
    },
  });
  
  const [error, setError] = useState<string>('');
  const name: string =  dataA?.getUser.name ??  '' ; // TODO: Check if can be replaced with JWT based data.
  const email: string = dataA?.getUser.email ??  '';
  const [personaData, setPersonaData] = React.useState<personaData>({
    email : email,
    userName: username,
    fullName: name,
  });
  // For closing and opening of the modal
  const [open, setOpen] = React.useState(false);
  const handleClose = () => {
    setOpen(false);
  };
  const handleUserChange = (e: any) => {
    setPersonaData({
      fullName: personaData.fullName,
      userName: e.target.value ,
      email: personaData.email,
    });
  };
  const handleNameChange = (e: any) => {
    const { name, value} = e.target;
    if(value!=="")
    setPersonaData({
      fullName: e.target.value,
      userName: personaData.userName,
      email: personaData.email,
    });
    else
    setPersonaData({
      fullName: "<your-name>",
      userName: personaData.userName,
      email: personaData.email,
    });
  };
  const handleEmailChange = (e: any) => {
    setPersonaData({
      fullName: personaData.fullName,
      userName: personaData.userName,
      email: e.target.value,
    });
  };
  const [updateDetails] = useMutation<UpdateUser>(UPDATE_DETAILS, {
    onCompleted: () => {
      setLoading(false);
      setOpen(true);
    },
    onError: (error) => {
      setLoading(false);
      setError(error.message as string);
      setOpen(true);
    },
    refetchQueries: [{ query: GET_USER, variables: { username } }],
  });
  // Submit entered data to /update endpoint
  const handleSubmit = () => {
    setLoading(true);
    fetch(`${config.auth.url}/update/details`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${getToken()}`,
      },
      body: JSON.stringify({
        name: personaData.fullName,
        email: personaData.email,
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        if ('error' in data) {
          setError(data.error_description as string);
          setLoading(false);
          setOpen(true);
        } else {
          updateDetails({
            variables: {
              user: {
                id: dataA?.getUser.id,
                name: personaData.fullName,
                email: personaData.email,
              },
            },
          });
        }
      })
      .catch((err) => {
        setError(err.message as string);
        setOpen(true);
        setLoading(false);
        console.error(err);
      });
  };
  return (
    <div>
      <form>
        <UserDetails
          nameValue={ personaData.fullName?personaData.fullName: memberDetails?(memberDetails.name):''}
          isUsernameDisabled
          handleNameChange={handleNameChange}
          emailValue={personaData.email?personaData.email:memberDetails?(memberDetails.email):''}
          handleEmailChange={handleEmailChange}
          userValue={personaData.userName}
          handleUserChange={handleUserChange}
          isNameDisabled={false}
          isEmailDisabled={false}
        />
        <div className={classes.saveButton}>
          <div data-cy="save">
            <ButtonFilled
              disabled={!(personaData.fullName.length && !loading)}
              onClick={handleSubmit}
            >
              {loading ? (
                <div>
                  <Loader size={20} />
                </div>
              ) : (
                <>
                  {t('settings.accountsTab.personalDetails.button.saveChanges')}
                </>
              )}
            </ButtonFilled>
          </div>
          <Modal
            open={open}
            onClose={handleClose}
            modalActions={
              <ButtonOutlined onClick={handleClose}>&#x2715;</ButtonOutlined>
            }
          >
            {error.length ? (
              <div className={classes.errDiv}>
                <div className={classes.textError}>
                  <Typography className={classes.typo} align="center">
                    <strong>
                      {t(
                        'settings.accountsTab.personalDetails.modal.headerErrStrong'
                      )}
                      :
                    </strong>{' '}
                    {t('settings.accountsTab.personalDetails.modal.headerErr')}
                  </Typography>
                </div>
                <div className={classes.textSecondError}>
                  <Typography className={classes.typoSub}>
                    {t(
                      'settings.accountsTab.personalDetails.modal.headerErrStrong'
                    )}
                    : {error}
                  </Typography>
                </div>
                <div data-cy="done" className={classes.buttonModal}>
                  <ButtonFilled onClick={handleClose}>
                    <>{t('settings.accountsTab.personalDetails.button.done')}</>
                  </ButtonFilled>
                </div>
              </div>
            ) : (
              <div className={classes.body}>
                <img src="./icons/userLarge.svg" alt="user" />
                <div className={classes.text}>
                  <Typography className={classes.typo} align="center">
                    {t('settings.accountsTab.personalDetails.modal.header')}{' '}
                    <strong>
                      {t(
                        'settings.accountsTab.personalDetails.modal.headerStrong'
                      )}
                    </strong>
                  </Typography>
                </div>
                <div className={classes.text1}>
                  <Typography align="center" className={classes.typo1}>
                    {t('settings.accountsTab.personalDetails.modal.info')}
                  </Typography>
                </div>
                <div data-cy="done">
                  <ButtonFilled onClick={handleClose}>
                    <>{t('settings.accountsTab.personalDetails.button.done')}</>
                  </ButtonFilled>
                </div>
              </div>
            )}
          </Modal>
        </div>
      </form>
    </div>
  );
};
export default PersonalDetails;


`

**Comment by duttaANI** [comment]
@Saranya-jena  I would like to work on this issue if possible.

**Comment by Rahul7171** [comment]
can I Work on this issue?

**Comment by Saranya-jena** [comment]
Hi @Rahul7171, thankyou for showing interest in LitmusChaos. This issue has been fixed by @duttaANI . You may take a look at other issues as well!
