### ISSUE TITLE
Support draining multiple in the node-drain experiment

### ISSUE THREAD

**Issue by andrewhu-hcl** [litmuschaos/litmus#3343]
Current node drain experiment, if the targetNodes is provided,  it will get all the node names by split the comma and check each node status. However, during the node drain stage, it just passed the targetNodes into the node drain command, didn’t check if a string contained multiple nodes with comma-separated. So it will cause an error if we specify the targetNodes as multiple node name list by comma-separated. It will be great if it can support draining the multiple nodes.

**Comment by neelanjan00** [comment]
Hi Andrew, thanks for creating this issue. The node drain experiment by design only supports one node, as also mentioned in the experiment docs. This is because the experiment has a high blast radius: it affects multiple applications that are scheduled on the node. Increasing the blast radius further by allowing multiple nodes can potentially accidentally affect critical applications.
