### ISSUE TITLE
Need understand if litmus supports OpenShift platform or not? .If it does how can we install it any doc or link would be of great help. If it doesn't support then can anyone suggest any other chaos tools that will support OpenShift platform and is non based saas tool? 

### ISSUE THREAD

**Issue by Aninditasrivastava** [litmuschaos/litmus#3778]
## Question
Feel free to get your queries resolved.

**Please make sure you have,**

- Reviewed the [Questions](https://github.com/litmuschaos/litmus/labels/question) asked by our community members and contributers.
- Searched opened and closed [GitHub issues](https://github.com/litmuschaos/litmus/issues)

**We primarily use GitHub as an issue tracker; for usage and support questions, please check out these resources below. Thanks!**

  - [LitmusChaos Readme](https://github.com/litmuschaos/litmus)
  - [LitmusChaos Docs](https://docs.litmuschaos.io/docs/next/getstarted.html)

**Comment by neelanjan00** [comment]
Hi @Aninditasrivastava, LitmusChaos does fully support and run on OpenShift platform. The installation steps are the same as installing any other k8s application on OpenShift. While we don't have a dedicated guide for it yet, please refer to the following blog to get an idea of how to get started. Please note that the blog is a bit old and LitmusChaos has released many stable versions since.

https://cloud.redhat.com/blog/chaos-engineering-with-litmuschaos
