### ISSUE TITLE
[LFX-Q2]: Enhance/improve chaos center code base and redesign chaos workflow apis

### ISSUE THREAD

**Issue by imrajdas** [litmuschaos/litmus#3970]
**This task is divided into multiple subtasks.**
* Refactor the [chaos-workflow](https://github.com/litmuschaos/litmus/tree/master/litmus-portal/graphql-server/pkg/chaos-workflow) pkg into interfaces and split the chaos-workflow and chaos-workflow run into separate pkg

* Resolve security vulnerability and golangci-lints of chaos-center backend components ([Graphql Server](https://github.com/litmuschaos/litmus/tree/master/litmus-portal/graphql-server), [Subscriber](https://github.com/litmuschaos/litmus/tree/master/litmus-portal/cluster-agents/subscriber), [Auth-Server](https://github.com/litmuschaos/litmus/tree/master/litmus-portal/authentication))

* Add unit test cases for  chaos-center backend components

* Refactor chaos-subscriber codebases and add interfaces for the functions

* Currently, our users are facing difficulty to use chaos workflow graphql APIs, so, we need to redesign the chaos workflow and workflow run APIs

Additional/Optional

Repository Ref:
* https://github.com/litmuschaos/litmus/tree/master/litmus-portal
* https://github.com/litmuschaos/litmus/wiki/ChaosCenter-Development-Guide (It's a little bit outdated, let us know if you face any difficulty with setup)

Note:
* Candidate should know Golang, Kubernetes, and backend development. It's okay if the individual is not familiar with litmuschaos.

**Comment by Swapnil-2502** [comment]
Is it too late to start reading documentation to understand the project and apply for LFX mentorship under your organisation.

**Comment by imrajdas** [comment]
@Swapnil-2502 - please send your proposal to lfx. We will review

**Comment by money8203** [comment]
Hey @imrajdas,

I'd love to work on this project as a part of LFX mentorship . As I am learning go, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience. Looking forward to contributing to the project's success.

**Comment by maheshkasabe** [comment]
Hello @imrajdas 

I would really love to work on this issue as it perfectly aligns with my current Technical skills as i'm quite familiar with Kubernetes and Backend Developement, and i would really love to take this issue hands-on and work around it! will you mention any of IRC channels so i can explain and learn more about this issue ?

**Comment by SD-13** [comment]
@imrajdas Just curious about what are the difficulties users are facing for Graphql API that can be resolved by REST API. Can you please shed some light on this or refer to any discussion about this? Thanks!

**Comment by achiverram28** [comment]
@imrajdas Hello  mentor for the LFX Mentorship program -> CNCF - LitmusChaos: Migrate chaos workflow api from graphql to rest and improve chaos center code 
 I am Ram Samarth B B , a 2nd year undergrad pursuing my BTech in Computer Science and Engineering at Indian Institute of Information Technology Kottayam . I am deep DevOps and Cloud Native enthusiast , especially Kubernetes and have been working on learning it in deep . I came across this project in LFX Mentorship . I would really like to learn the working of the litmus , and would like to contribute to this project under this mentorship . I have a string hold on Kubernetes , configuration , API  development, Open Application  model . Please help me how to contribute to this project . I would give my best to work on it.I am also working on the setting up of the project . I want the guidance of the mentor @imrajdas  
. Please help me out

**Comment by imrajdas** [comment]
Hi applicants, there is a slight change in this issue. 

This issue will focus more on the chaos center code base enhancement than the chaos workflow API changes.

**Comment by imrajdas** [comment]
Hi all, Please submit your applications before the deadline

**Comment by achiverram28** [comment]
> Hi applicants, there is a slight change in this issue.
> 
> This issue will focus more on the chaos center code base enhancement than the chaos workflow API changes.

Sure , now worries

**Comment by achiverram28** [comment]
> Hi all, Please submit your applications to LFX portal before the deadline

Have submitted

**Comment by Aadeesh11** [comment]
> Hi all, Please submit your applications to LFX portal before the deadline

Submitted! Setting up the project!

**Comment by SohamRatnaparkhi** [comment]
> Hi applicants, there is a slight change in this issue.
> 
> This issue will focus more on the chaos center code base enhancement than the chaos workflow API changes.

Thank you @imrajdas for giving this update.
I have updated my proposal to this project, and submitted it on LFX website.

I am extremely enthusiastic about the opportunity to learn and contribute to LitmusChaos. I am confident that my skills and experience make me a strong candidate to make meaningful contributions to this project.

**Comment by prajak002** [comment]
Hi @imrajdas  I am Prajak Sen, a pre-final year student at IEM Kolkata, India.  i have 3+ years of experiences in backend development , i have worked with Go and Kubernetes in my past days, i have followed the code base of litmus chaos portal  , and seen the architectural workflow of chaos and the pkg underlying the graphql-server directory of the reference repository.


1. ### spliting the chaos-workflow and chaos-workflow run into separate pkg
here we can  split  the chaos-workflow into seperate interfaces in this manner :- 


modified chaos_workflow.go should be looked like this
```
// File: litmus-portal/graphql-server/pkg/chaos-workflow/chaos_workflow.go

package workflow

type WorkflowClient interface {
	CreateWorkflow() error
	GetWorkflowByID(id string) (*Workflow, error)
	// Other methods...
}

type ExperimentClient interface {
	CreateExperiment() error
	GetExperimentByID(id string) (*Experiment, error)
	// Other methods...
}

type WorkflowTemplateClient interface {
	CreateTemplate() error
	GetTemplateByID(id string) (*WorkflowTemplate, error)
	// Other methods...
}

type ChaosWorkflow struct {
	WorkflowClient
	ExperimentClient
	WorkflowTemplateClient
	// Other fields...
}

// Other struct definitions and implementations...
```

again we can build chaos-workflow_run.go in this way to run the workflow  instance

```
// File: litmus-portal/graphql-server/pkg/chaos-workflow-run/chaos_workflow_run.go

package workflowrun

import "litmus-portal/graphql-server/pkg/chaos-workflow"

type WorkflowRunManager interface {
	RunWorkflow(workflowID string) error
	GetWorkflowRunStatus(runID string) (string, error)
	// Other methods...
}

type ChaosWorkflowRun struct {
	WorkflowRunManager
	// Other fields...
}

// Other struct definitions and implementations...

```
2. ### redesigning  the chaos workflow and workflow run APIs
 to  build a strongly-typed schema  for  the  chaos workflow graphql  api , we can  design  this schema in this way :- 
   
```
type Workflow {
  id: ID!
  name: String!
  description: String!
  templateId: ID!
  parameters: Parameters!
}

type Parameters {
  param1: String!
  param2: String!
  # Add more parameters as needed
}

input CreateWorkflowInput {
  name: String!
  description: String!
  templateId: ID!
  parameters: ParametersInput!
}

input ParametersInput {
  param1: String!
  param2: String!
  # Add more parameters as needed
}

type Query {
  workflow(id: ID!): Workflow
  # Add more queries as needed
}

type Mutation {
  createWorkflow(input: CreateWorkflowInput!): Workflow
  updateWorkflow(id: ID!, input: CreateWorkflowInput!): Workflow
  deleteWorkflow(id: ID!): ID
  # Add more mutations as needed
}

```

here, a Workflow type with its properties such as id, name, **description**, **templateId**, and **parameters**. The Parameters type represents the set of parameters for a workflow.

The **CreateWorkflowInput** input type is used for creating a new workflow, while the ParametersInput input type is used for specifying the parameters.

The Query type provides a single query field workflow to retrieve a specific workflow by its ID. You can extend this type with more queries based on your requirements.

The **Mutation** type defines mutation fields to create, update, and delete workflows. You can add more mutation fields as needed to fulfill other operations.

3. ### Refactor chaos-subscriber codebases and add interfaces for the functions
When refactoring the chaos-subscriber codebase and adding interfaces for the functions in a Kubernetes-based environment, we  need to consider the specific requirements and interactions with Kubernetes resources.

we may implement in this way 🥇 
```
package main

import (
	"fmt"
	"log"
	"os"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)

// Interface for Kubernetes resource operations
type KubernetesClient interface {
	GetPods(namespace string) ([]corev1.Pod, error)
}

// Implementation of KubernetesClient interface using the official Kubernetes client library
type OfficialKubernetesClient struct {
	clientset *kubernetes.Clientset
}

func NewOfficialKubernetesClient(kubeconfigPath string) (*OfficialKubernetesClient, error) {
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfigPath)
	if err != nil {
		return nil, err
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, err
	}

	return &OfficialKubernetesClient{
		clientset: clientset,
	}, nil
}

func (c *OfficialKubernetesClient) GetPods(namespace string) ([]corev1.Pod, error) {
	pods, err := c.clientset.CoreV1().Pods(namespace).List(metav1.ListOptions{})
	if err != nil {
		return nil, err
	}

	return pods.Items, nil
}

// Example usage
func main() {
	kubeconfigPath := os.Getenv("KUBECONFIG")
	if kubeconfigPath == "" {
		log.Fatal("KUBECONFIG environment variable is not set")
	}

	// Create an instance of the Kubernetes client
	client, err := NewOfficialKubernetesClient(kubeconfigPath)
	if err != nil {
		log.Fatalf("Failed to create Kubernetes client: %v", err)
	}

	// Get pods from a specific namespace
	pods, err := client.GetPods("default")
	if err != nil {
		log.Fatalf("Failed to get pods: %v", err)
	}

	// Process the pods
	for _, pod := range pods {
		fmt.Printf("Pod: %s\n", pod.Name)
		// Perform your desired operations with the pod
	}
}
```
we define the **KubernetesClien**t interface that represents the operations we want to perform on Kubernetes resources. The **OfficialKubernetesClient** struct implements the interface using the official Kubernetes client library for Go.

The **NewOfficialKubernetesClien**t function creates an instance of **OfficialKubernetesClient** by initializing the Kubernetes client using the provided kubeconfig file path.

The GetPods method of **OfficialKubernetesClient** retrieves a list of pods from the specified namespace using the Kubernetes client library.

In the main function, we create an instance of **OfficialKubernetesClien**t and demonstrate how to use the GetPods method to retrieve and process pods from the "default" namespace.

Make sure to have the necessary dependencies, such as the Kubernetes client Go library (k8s.io/client-go), imported into your project.

Set the **KUBECONFIG** environment variable with the path to your **kubeconfig** file before running the program.

4. ### previous works
i have also tried to modify the  center code base enhancement   i.e. "Enhance/Upgrade chaos operator and chaos exporter module"  and here this is my   brief idea of implementing this enhancement :[https://github.com/litmuschaos/litmus/issues/3969](url)

so that will be fine tuned 

I would love to be a part of this beautiful community and looking forward to a positive reply
Thank you  :)

**Comment by imrajdas** [comment]
Hi all, Today(May 23, 5:00 PM PDT) is the last day to submit your proposal to the LFX portal

Apply link- https://mentorship.lfx.linuxfoundation.org/project/983193ea-9cca-405f-baa5-e6ade4df1ba2

**Comment by imrajdas** [comment]
Hi All, We have finalized the LFX mentee. We participate in LFX every 3 months. Please apply it for next term in case you didn't get selected.

Please feel free to contribute to the LitmusChaos project or join a community call to learn about the project.
