### ISSUE TITLE
UI shows invalid probe configuration when experiment is `in progress` / `running`

### ISSUE THREAD

**Issue by smitthakkar96** [litmuschaos/litmus#4252]
**What happened**:

We configured a probe with `Continuous` mode in the fault as shown in the screenshot below

<img width="683" alt="Screenshot 2023-11-01 at 14 10 13" src="https://github.com/litmuschaos/litmus/assets/10204970/133b9b0c-7d4f-4d1c-8bcb-3cb54c2f19f9">

While running the experiment, it shows `SOT` (start of the test), as shown in the screenshot below. Also if you notice, the status is always `N/A`

<img width="487" alt="Screenshot 2023-11-01 at 14 11 07" src="https://github.com/litmuschaos/litmus/assets/10204970/630034ba-6558-4085-9aa3-b452cc19c548">

If you see the finished experiment run it shows the status and configuration correctly

<img width="531" alt="Screenshot 2023-11-01 at 14 11 54" src="https://github.com/litmuschaos/litmus/assets/10204970/96eba51d-e903-4623-be53-4b9aa782013b">

**What you expected to happen**:

Probe status and mode should be shown correctly when viewing the running experiment.

**Comment by vanshBhatia-A4k9** [comment]
@S-ayanide can you please re-produce and take a look at this issue.

**Comment by S-ayanide** [comment]
Hey @smitthakkar96 thanks for creating this issue, the status for the probes are always mapped to the execution result from the point it's been picked up by the subscriber, as soon as its picked up the status would shift to `Awaited` and either to `Passed` or `Failed` post completion, till that time it defaults to `N/A` since its not a part of the chaos result returned.

For the incorrect status bug that is reported, we've provided a fix for the same on version 3.1.0 and above. Feel free to reopen this issue if you feel this bug wasn't addressed.

**Comment by smitthakkar96** [comment]
I can confirm this is still happening on 3.1.0
