### ISSUE TITLE
Operation "create" missing from k8sprobes in 3.1.0

### ISSUE THREAD

**Issue by nwinstel-insight** [litmuschaos/litmus#4335]
**What happened**: under operation while creating a resilience probe there is no create option:
![Screenshot 2023-12-14 at 6 53 10 AM](https://github.com/litmuschaos/litmus/assets/105605527/d6e0fb4b-1486-40c1-8ad1-6243b02bd057)

However [the documentation states there is a create operation](https://litmuschaos.github.io/litmus/experiments/concepts/chaos-resources/probes/k8sProbe/) We need a way to be able to create Kubernetes objects and kinds. Is there a new way to do this that is not documented?

**What you expected to happen**: I would expect all operations to be present in the UI

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**: make a k8sprobe and look at the operations

**Anything else we need to know?**: Please read this issue. thank you.

**Comment by S-ayanide** [comment]
Hey @nwinstel-insight , thanks for creating this issue, the `create` operation is k8s probe is intentionally not provided in the Resilience Probe UI yet, but still supported with the older flow or using inline probe, the reason its not present in the UI yet is because of a CRD update required to scope the `data` field inside `k8sProbe` input details. However, this is not a blocker for executing k8s probes with this specific operation, if you want to work with this operation, the solution for now is to use inline k8s probe like the older flow and provide the operation along with data field.
