### ISSUE TITLE
After deleting a resilience probe you can never use that same name ever again

### ISSUE THREAD

**Issue by nwinstel-insight** [litmuschaos/litmus#4377]
**What happened**: I deleted a probe to change it from a k8s probe to a prom probe (now that prom probes actually work). When I went to reuse the name it forbid it.

**What you expected to happen**: When I delete a probe I want it gone so that I can use the name again if I choose.

**Where can this issue be corrected? (optional)**

**How to reproduce it (as minimally and precisely as possible)**: create a probe of any type named test, delete the probe, try to create a new probe by the name test

**Anything else we need to know?**:

**Comment by S-ayanide** [comment]
Thanks for creating the issue, 

The name of the probe itself is treated as a unique identifier for he probe entity, so reusing of probe names even after deletion is not supported. 

Since we need to attach a probe in the manifest mandatorily (The rationale behind this is mentioned [here](https://github.com/litmuschaos/litmus/issues/4232#issuecomment-1805140080)) we wanted to keep human readable IDs, in this case the name of the probe (in the manifest as probeRef). It wouldn't be very helpful if users have to remember the UUID each time they edit or create a manifest. That is the primary reason behind making the name as a unique ID.

We are aware that not able to rename a probe might cause inconvenience and thus are working on a force delete approach which'd clear up the ID for you to use again. Unfortunately its a WIP right now, but for the moment you can only name it once at creation time.
