### ISSUE TITLE
Relevant Changes/ Refactoring of the Page : https://docs.litmuschaos.io/docs/next/chaos.html

### ISSUE THREAD

**Issue by rahulchheda** [litmuschaos/litmus#763]
## DOCUMENTATION
 
**What to do**:

- Refactor the Page in the title

**Where to create the PR**
- https://github.com/litmuschaos/litmus-docs

**Comment by mohatagarvit** [comment]
Hi, I checked the [chaos](https://github.com/litmuschaos/litmus-docs/edit/master/docs/chaos.md) doc. Are we trying to refactor the script in this? Because I don't think anything else can be refactored and since many of the docs have the same issue and the same script. 

So I am guessing it is the script but I am not able to figure out what to refactor in this?

**Comment by ksatchit** [comment]
This page, with the content in the said format is not being used in the recent version of the docs.
