### ISSUE TITLE
Document or collate the failure testing scenarios for Kafka on Kubernetes

### ISSUE THREAD

**Issue by umamukkara** [litmuschaos/litmus#822]
## Is this a BUG REPORT or FEATURE REQUEST?
 
**FEATURE REQUEST**

Kafka / Strimzi is being increasingly adopted on Kubernetes environment. Litmus team wants to collaborate with community and build a Chaos Chart for Apache Kafka on Kubernetes. The first step in doing so, is to identify the failure scenarios that can affect Kafka in production.

Useful links:
https://github.com/litmuschaos/litmus
https://hub.litmuschaos.io/

Anyone who wishes to contribute to this issue, can comment on this issue in the following format.

Fault injection:
Expected behavior in HA deployments:
Impact if weakness is found :

**Comment by ksatchit** [comment]
Additional Reference: https://github.com/litmuschaos/litmus/issues/183#issue-363248737

**Comment by bhaumik1802** [comment]
@ksatchit 
As discussed with Kartik - Please find some use cases for Kafka Chaos expertiments

Question: what happens when the message queue becomes 100ms slower due to load.
The Hypothesis: The application layer will see slower commits, memory utilization will increase due to a larger queue depth, and eventually the queue will overrun and the application will lose data

Question: What happens when we experience packet loss between our application and the message queue?
The Hypothesis: Much like the latency test, we expect queues to fill, potentially losing some data due to failure to complete a transaction

Question : Will my Kafka cluster survive the loss of a single broker node? Two?
The Hypothesis: steady-state capacity should be calculated to suffer the loss of selected nodes, the load should increase on remaining nodes, producers and consumers should see no impact

Question: What happens when my distributed storage fails?
The Hypothesis: I’m going to lose the entire cluster.

Question: what happens when one ZooKeeper node, maybe the leader node, has decided ntp is not worth syncing to.
The Hypothesis: We assume the other ZooKeeper nodes should be able to form a quorum and kibosh the misbehaving node, this will verify this assumption.

**Comment by umamukkara** [comment]
Thank you @bhaumik1802

**Comment by ksatchit** [comment]
The experiments mentioned here have been implemented and are available for use. 

Moreover, Litmus has added multiple new faults as well as probe types - which allows users to target any Kubernetes service along with custom app-specific validations - thereby removing the need for separate category/type of experiments.

What is needed is creation of newer usecase docs describing useful chaos experiments on popular applications.

Closing this issue now. We will create separate tasks when we work on the respective docs.
